FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    bash \
    python3 \
    python3-pip \
    python3-dev \
    postgresql

RUN mkdir /src
ADD ./backend src/
WORKDIR /src

RUN pip3 install -r requirements.txt

CMD ["python3", "./api.py"]