FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y \
    bash \
    python3 \
    python3-pip

RUN mkdir /src
ADD ./backend src/
WORKDIR /src

RUN pip3 install -r requirements.txt --break-system-packages

EXPOSE 5000
CMD ["python3", "./api.py"]